import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { store } from '../app/store'
import { Provider } from 'react-redux'
import {Preguntas} from '../components/preguntas'
import {Modal} from '../components/Modal'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <main className={`${styles.main} ${inter.className}`}>
          <Preguntas/>
          <Modal/>
        </main>
      </Provider>
    </>
  )
}
